_wandb:
    value:
        cli_version: 0.22.0
        e:
            qgqqy0ym1szhkrip6s23vsy9wykwkj5k:
                args:
                    - --pickle_path
                    - ../movies_dataset/processed_data.pkl
                    - --use_wandb
                codePath: main_files/recommendation_system.py
                codePathLocal: recommendation_system.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "128915435520"
                        used: "90939699200"
                email: abdulahad17100@gmail.com
                executable: /home/onlyahad/miniconda3/envs/ml_global/bin/python
                git:
                    commit: 11eb5547a311ac12d5ebd3e413f2bd32032a2aa6
                    remote: https://github.com/OnlyAhad13/Recommendation-System-MAANG-NVIDIA-.git
                gpu: NVIDIA GeForce 920MX
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Maxwell
                      cudaCores: 256
                      memoryTotal: "2147483648"
                      name: NVIDIA GeForce 920MX
                      uuid: GPU-5f89661c-e007-9fe8-22c3-b87f2fa04619
                host: OnlyAhad
                memory:
                    total: "20868661248"
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: /home/onlyahad/Desktop/Recommendation System/main_files/recommendation_system.py
                python: CPython 3.11.11
                root: recsys_output
                startedAt: "2025-10-07T14:13:47.819900Z"
                writerId: qgqqy0ym1szhkrip6s23vsy9wykwkj5k
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 105
            "3":
                - 2
                - 3
                - 8
                - 16
                - 62
            "4": 3.11.11
            "5": 0.22.0
            "10":
                - 17
            "12": 0.22.0
            "13": linux-x86_64
batch_size:
    value: 4096
cross_layers:
    value: 3
ctr_weight:
    value: 0.3
distributed_strategy:
    value: none
dnn_dims:
    value:
        - 256
        - 128
        - 64
dropout_rate:
    value: 0.2
embedding_dim:
    value: 128
epochs_ranking:
    value: 5
epochs_retrieval:
    value: 5
eval_topk:
    value:
        - 5
        - 10
        - 20
        - 50
item_tower_dims:
    value:
        - 256
        - 128
l2_reg:
    value: 1e-05
learning_rate_ranking:
    value: 0.001
learning_rate_retrieval:
    value: 0.01
mixed_precision:
    value: true
negative_sampling_strategy:
    value: mixed
num_hard_negatives:
    value: 5
num_random_negatives:
    value: 50
rating_weight:
    value: 0.7
user_tower_dims:
    value:
        - 256
        - 128
warmup_steps:
    value: 1000
