_wandb:
    value:
        cli_version: 0.22.0
        e:
            1qk3txdhzmin21exin1apra4jgrnb1kk:
                args:
                    - --pickle_path
                    - processed_data.pkl
                    - --output_dir
                    - ./out_test
                    - --batch_size
                    - "256"
                    - --epochs_retrieval
                    - "1"
                    - --epochs_ranking
                    - "1"
                codePath: main_files/recommendation_system.py
                codePathLocal: recommendation_system.py
                email: abdulahad17100@gmail.com
                executable: /home/onlyahad/miniconda3/envs/ml_global/bin/python
                git:
                    commit: 11eb5547a311ac12d5ebd3e413f2bd32032a2aa6
                    remote: https://github.com/OnlyAhad13/Recommendation-System-MAANG-NVIDIA-.git
                host: OnlyAhad
                os: Linux-6.14.0-33-generic-x86_64-with-glibc2.39
                program: /home/onlyahad/Desktop/Recommendation System/main_files/recommendation_system.py
                python: CPython 3.11.11
                root: out_test
                startedAt: "2025-10-04T12:20:14.306361Z"
                writerId: 1qk3txdhzmin21exin1apra4jgrnb1kk
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
                - 105
            "2":
                - 2
                - 3
                - 5
                - 53
                - 105
            "3":
                - 16
            "4": 3.11.11
            "5": 0.22.0
            "12": 0.22.0
            "13": linux-x86_64
batch_size:
    value: 256
cross_layers:
    value: 3
ctr_weight:
    value: 0.5
distributed_strategy:
    value: mirrored
dnn_dims:
    value:
        - 512
        - 256
        - 128
        - 64
dropout_rate:
    value: 0.2
embedding_dim:
    value: 128
epochs_ranking:
    value: 1
epochs_retrieval:
    value: 1
eval_topk:
    value:
        - 1
        - 5
        - 10
        - 20
        - 50
        - 100
item_tower_dims:
    value:
        - 512
        - 256
        - 128
l2_reg:
    value: 1e-05
learning_rate_ranking:
    value: 0.001
learning_rate_retrieval:
    value: 0.001
mixed_precision:
    value: true
negative_sampling_strategy:
    value: mixed
num_hard_negatives:
    value: 5
num_random_negatives:
    value: 100
rating_weight:
    value: 0.5
user_tower_dims:
    value:
        - 512
        - 256
        - 128
warmup_steps:
    value: 1000
